package com.solarize.solarizeWebBackend.modules.schedule;

import java.time.LocalDateTime;

public class ScheduleBuilder {

    private ScheduleStatusEnum status = ScheduleStatusEnum.MARKED;
    private ScheduleTypeEnum type = ScheduleTypeEnum.NOTE;
    private LocalDateTime startDate = LocalDateTime.now();
    private LocalDateTime endDate = LocalDateTime.now().plusHours(1);
    private Boolean isActive = true;

    public static ScheduleBuilder builder() {
        return new ScheduleBuilder();
    }

    public ScheduleBuilder withStatus(ScheduleStatusEnum status) {
        this.status = status;
        return this;
    }

    public ScheduleBuilder withType(ScheduleTypeEnum type) {
        this.type = type;
        return this;
    }

    public ScheduleBuilder withFutureDate() {
        this.startDate = LocalDateTime.now().plusDays(1);
        this.endDate = this.startDate.plusHours(1);
        return this;
    }

    public ScheduleBuilder withPastDate() {
        this.startDate = LocalDateTime.now().minusDays(1);
        this.endDate = this.startDate.plusHours(1);
        return this;
    }

    public ScheduleBuilder withInactiveSchedule() {
        isActive = false;

        return this;
    }

    public Schedule build() {
        Schedule schedule = new Schedule();

        schedule.setId(1L);
        schedule.setStatus(this.status);
        schedule.setType(this.type);
        schedule.setStartDate(this.startDate);
        schedule.setEndDate(this.endDate);
        schedule.setTitle("Test Schedule");
        schedule.setDescription("Generated by ScheduleBuilder");
        schedule.setIsActive(isActive);

        return schedule;
    }
}
