app.env=prod

spring.datasource.url=jdbc:mysql://mysql-db:3306/solarway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=solarway
spring.datasource.password=06241234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.data.redis.host=${REDIS_HOST:redis-multidb}
spring.data.redis.port=6379

jwt.validity=21600000
jwt.secret=RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgc2VydmUgbyBVbml2ZXJzbyBlIHBvciBxdWUgZWxlIGVzdOEgYXF1aSwgZWxlIGRlc2FwYXJlY2Vy4SBpbnN0YW50YW5lYW1lbnRlIGUgc2Vy4SBzdWJzdGl0de1kbyBwb3IgYWxnbyBhaW5kYSBtYWlzIGVzdHJhbmhvIGUgaW5leHBsaWPhdmVsLiBFeGlzdGUgdW1hIHNlZ3VuZGEgdGVvcmlhIHF1ZSBkaXogcXVlIGlzc28gauEgYWNvbnRlY2V1Li4u

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL:dummy@email.com}
spring.mail.password=${PASSWORD_EMAIL:dummy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.storage.s3.bucket=${BUCKET_NAME:dummy-bucket}

aws.region=us-east-1

aws.accessKeyId=${AWS_ACCESS_KEY_ID:dummy}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:dummy}
aws.sessionToken=${AWS_SESSION_TOKEN:dummy}

solarize.security.bot-secret=${BOT_SECRET:solarize_whatsapp_bot_super_secret}