spring.profiles.active=dev

spring.application.name=solarize-web-backend

server.error.include-message=always
server.error.include-binding-errors=always

server.servlet.context-path=/api

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
retry.schedule.rate=60000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

broker.exchange.name=schedule.direct.exchange
broker.create-queue.name=schedule.create
broker.update-queue.name=schedule.update
broker.cancel-queue.name=schedule.cancel

